### ISSUE TITLE
Wunsch zu h2cdimage

### ISSUE THREAD

**Issue by ByteKrieger** [ctbo/h2rename#3]
Können sie den Quellcode für das beliebte h2cdimage veröffentlichen so kann das programm weiterentwickelt werden und geht nicht in vergessenheit ich kontaktiere sie hier um einen Wunsch zu äußern da ich keine andere Kontaktmöglichkeit gefunden habe.

Lg ein begeisterter ct leser seit 15 Jahren 
Markus

**Comment by ctbo** [comment]
Am 06.09.21 um 05:07 schrieb ByteKrieger:
> Können sie den Quellcode für das beliebte h2cdimage veröffentlichen so kann das programm weiterentwickelt werden und geht nicht in vergessenheit ich kontaktiere sie hier um einen Wunsch zu äußern da ich keine andere Kontaktmöglichkeit gefunden habe.
> 

Erstaunlich, wie lange sich H2cdimage gehalten hat ;-).

Leider kann ich den Quellcode nicht veröffentlichen, weil er eine 
Library benutzt, die ich nicht veröffentlichen darf. Ein befreundeter 
Entwickler hat mir erlaubt, sie zu benutzen, ich kann sie aber nicht 
weitergeben.

Schauen Sie sich doch einmal dvdisaster an. Der Autor hat damals nach 
der Veröffentlichung von H2cdimage dessen Lesestrategie integriert und 
das Programm kann noch eine Menge mehr. Ich habe es allerdings aus den 
Augen verloren und weiß nicht, ob und wie es sich weiterentwickelt hat.


> Lg ein begeisterter ct leser seit 15 Jahren 
> Markus

Ich bin ja nun seit mehr als vier Jahren nicht mehr bei c't. Viele Grüße 
aus Down Under

Harald Bögeholz
